[package]
name = "push-byceps-stats-to-discord"
version = "0.2.0"
authors = ["Jochen Kupperschmidt"]
edition = "2021"
description = "Push BYCEPS ticket sale stats to Discord (as channel name)"
readme = "README.md"
repository = "https://github.com/byceps/push-byceps-stats-to-discord"
license = "MIT"
keywords = ["discord"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0"
clap = { version = "2.33.3", default-features = false }
serde = { version = "1", features = ["derive"] }
toml = "0.5.8"
ureq = { version = "2.2.0", features = ["json"] }
